import { randomUUID } from "node:crypto";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Server side of the Contribution Workspace: a human's questions about a run, and the
 * changes they request to its patch.
 *
 * Both work only from the run's public payload -- the same data the dashboard already
 * receives -- so nothing private (session ids, approval checkpoints, tokens) can reach a
 * model prompt or a response through them.
 *
 * A change request is recorded against the run, not acted on: nothing here edits a patch,
 * re-runs tests, or starts an agent turn. The page says so.
 */

export interface ChangeRequest {
  id: string;
  runId: string;
  text: string;
  createdAt: string;
  /** The patch the request was made against, so a later revision can show what it answers. */
  patchHash?: string;
  /**
   * Always "recorded" today: Squasher does not yet implement requested changes. The field
   * exists so a future implementation can move it to "in-progress" and "implemented".
   */
  status: "recorded";
}

const changeRequestsFile = "change-requests.jsonl";
const maxChangeRequestChars = 2_000;
const maxQuestionChars = 1_000;

export async function recordChangeRequest(
  dataDir: string,
  input: { runId: string; text: unknown; patchHash?: string }
): Promise<ChangeRequest> {
  if (typeof input.text !== "string" || input.text.trim().length < 3) {
    throw new WorkspaceInputError("A change request needs at least a few words describing the change");
  }
  const request: ChangeRequest = {
    id: `change-${randomUUID()}`,
    runId: input.runId,
    text: input.text.trim().slice(0, maxChangeRequestChars),
    createdAt: new Date().toISOString(),
    ...(input.patchHash ? { patchHash: input.patchHash } : {}),
    status: "recorded"
  };
  await mkdir(dataDir, { recursive: true });
  await appendFile(join(dataDir, changeRequestsFile), `${JSON.stringify(request)}\n`, "utf8");
  return request;
}

export async function readChangeRequests(dataDir: string | undefined, runId: string): Promise<ChangeRequest[]> {
  if (!dataDir) return [];
  let text: string;
  try {
    text = await readFile(join(dataDir, changeRequestsFile), "utf8");
  } catch {
    return [];
  }
  return text
    .split("\n")
    .flatMap((line) => {
      if (!line.trim()) return [];
      try {
        const parsed = JSON.parse(line) as ChangeRequest;
        return parsed.runId === runId ? [parsed] : [];
      } catch {
        return [];
      }
    });
}

export class WorkspaceInputError extends Error {}

/** The minimal model interface; the harness's LlmClient satisfies it. */
export interface AskModel {
  complete(messages: Array<{ role: "system" | "user"; content: string }>, tools: never[]): Promise<{ text: string }>;
}

export interface AskAnswer {
  question: string;
  answer: string;
  /** Which parts of the run were available to answer from, so the page can say what was not. */
  contextSections: string[];
  missingSections: string[];
  answeredAt: string;
}

const askInstructions = [
  "You are Squasher, answering a maintainer's question about one of your own runs.",
  "Answer ONLY from the run context below. It is everything you know about this run.",
  "If the context does not contain what the question needs, say exactly which information is unavailable. Never guess, and never invent files, lines, tests, results or requirements.",
  "Refer to concrete file paths, requirement text and recorded test output from the context. Keep the answer short: a few sentences or a short list.",
  "The patch was generated by Squasher, an automated agent. Never describe it as written by a human.",
  "Distinguish what was verified by executed evidence from what the agent only reported, and from what the issue discussion merely claimed."
].join("\n");

/**
 * Builds the context a question is answered from, from the public run payload only. Each
 * section is bounded; a section with nothing in it is reported as missing, not filled in.
 */
export function buildAskContext(run: Record<string, unknown>): { text: string; sections: string[]; missing: string[] } {
  const sections: Array<[string, string | undefined]> = [];
  const result = record(record(run.trueForge).result);
  const outcome = record(run.outcome);
  const statuses = record(run.statuses);

  sections.push(["Issue", joinDefined([str(run.repository) && `Repository: ${str(run.repository)}`, str(run.issueTitle) && `Title: ${str(run.issueTitle)}`, clip(str(run.issueBody), 4_000)])]);
  sections.push(["Issue discussion", clip(str(run.issueDiscussion), 6_000)]);
  sections.push([
    "Run status",
    joinDefined([
      str(record(statuses.implementation).label) && `Implementation: ${str(record(statuses.implementation).label)} -- ${str(record(statuses.implementation).reason)}`,
      str(record(statuses.contribution).label) && `Contribution: ${str(record(statuses.contribution).label)} -- ${str(record(statuses.contribution).reason)}`,
      str(outcome.headline) && `Outcome: ${str(outcome.headline)}`,
      str(result.status) && `Result status: ${str(result.status)}`
    ])
  ]);
  sections.push(["Agent summary", clip(str(result.summary), 4_000)]);
  sections.push(["Requirements", list(result.requirements, (entry) => `- [${str(entry.verdict)}] ${str(entry.requirement)} -- evidence: ${str(entry.evidence) ?? "none recorded"}${record(entry.ownership).by ? ` (owned by ${str(record(entry.ownership).by)})` : ""}`)]);
  sections.push(["Discussion claims checked", list(result.discussionClaims, (entry) => `- [${str(entry.verdict)}] ${str(entry.claim)} -- repository shows: ${str(entry.evidence)}`)]);
  sections.push(["File change explanations", list(result.fileChanges, (entry) => `- ${str(entry.path)}: ${str(entry.summary)}${Array.isArray(entry.requirements) ? ` (requirements: ${entry.requirements.join("; ")})` : ""}`)]);
  sections.push(["Findings", list(result.findings, (entry) => `- ${String(entry)}`, true)]);
  const proof = record(result.proof);
  sections.push([
    "Tests and proof",
    joinDefined([
      str(proof.attempts) && `Attempts: ${clip(str(proof.attempts), 1_500)}`,
      str(proof.before) && `Before: ${clip(str(proof.before), 1_500)}`,
      str(proof.after) && `After: ${clip(str(proof.after), 1_500)}`,
      str(proof.regressions) && `Regression checks: ${clip(str(proof.regressions), 1_500)}`
    ])
  ]);
  const patch = record(result.candidatePatch);
  const diffs = Array.isArray(result.patchDiff) ? result.patchDiff.map(record) : [];
  sections.push([
    "Patch",
    Array.isArray(patch.files)
      ? joinDefined([
          str(patch.title) && `Title: ${str(patch.title)}`,
          clip(str(patch.body), 3_000),
          ...patch.files.map(record).map((file) => {
            const base = diffs.find((diff) => diff.path === file.path);
            const change = base ? (str(base.change) === "added" ? "added" : "modified") : "base content unknown";
            return `--- ${str(file.path)} (${change})\n${clip(str(file.content), 6_000)}${base && str(base.before) ? `\n--- original ${str(file.path)}\n${clip(str(base.before), 4_000)}` : ""}`;
          })
        ])
      : undefined
  ]);
  const policy = record(run.policy);
  sections.push([
    "Contribution policy",
    str(policy.label) ? `${str(policy.label)}: ${str(policy.detail)}${list(policy.signals, (signal) => `\n- ${str(signal.kind)} (${str(signal.path)}): "${str(signal.excerpt)}"`, true) ?? ""}` : undefined
  ]);

  const present = sections.filter(([, body]) => body && body.trim());
  const missing = sections.filter(([, body]) => !body || !body.trim()).map(([name]) => name);
  const text = present.map(([name, body]) => `## ${name}\n${body}`).join("\n\n");
  return { text: text.slice(0, 60_000), sections: present.map(([name]) => name), missing };
}

export async function askAboutRun(model: AskModel, run: Record<string, unknown>, question: unknown): Promise<AskAnswer> {
  if (typeof question !== "string" || question.trim().length < 3) {
    throw new WorkspaceInputError("Ask a question of at least a few words");
  }
  const trimmed = question.trim().slice(0, maxQuestionChars);
  const context = buildAskContext(run);
  const response = await model.complete(
    [
      { role: "system", content: askInstructions },
      {
        role: "user",
        content: [
          "# Run context",
          context.text,
          context.missing.length ? `\n(Not available for this run: ${context.missing.join(", ")}.)` : "",
          "",
          "# Question",
          trimmed
        ].join("\n")
      }
    ],
    []
  );
  return {
    question: trimmed,
    answer: response.text.trim() || "No answer was returned.",
    contextSections: context.sections,
    missingSections: context.missing,
    answeredAt: new Date().toISOString()
  };
}

function record(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function str(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

function clip(value: string | undefined, max: number): string | undefined {
  if (!value) return undefined;
  return value.length > max ? `${value.slice(0, max)}\n[... truncated ...]` : value;
}

function joinDefined(parts: Array<string | undefined | false>): string | undefined {
  const kept = parts.filter((part): part is string => typeof part === "string" && part.trim().length > 0);
  return kept.length ? kept.join("\n") : undefined;
}

function list(value: unknown, render: (entry: Record<string, unknown>) => string, raw = false): string | undefined {
  if (!Array.isArray(value) || value.length === 0) return undefined;
  return value.map((entry) => (raw && typeof entry === "string" ? render(entry as never) : render(record(entry)))).join("\n");
}
