import {
  AlertTriangle,
  ArrowLeft,
  Bot,
  Check,
  ClipboardCheck,
  Copy,
  Download,
  FileCode2,
  FileDiff,
  GitPullRequestArrow,
  ListChecks,
  MessageSquareText,
  PencilLine,
  RefreshCw,
  Scale,
  Send,
  ShieldCheck,
  TestTube2,
  X
} from "lucide-react";
import { useId, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import type { AskAnswer } from "./approval-client";
import type { ApprovalActionId, ChangeRequestView, DashboardRun } from "./data";
import { unifiedPatch, type FileDiff as FileDiffModel } from "./diff";
import { MarkdownContent } from "./MarkdownContent";
import { PanelTitle, SourceTag } from "./Outcome";
import { buildWorkspace, type WorkspaceFile, type WorkspaceModel } from "./workspace-model";

/**
 * The Contribution Workspace: where a human reviews a verified patch before any contribution.
 *
 * Review, understand, approve -- or request changes first. Everything shown comes from the
 * run. What is not wired up yet (re-running tests, applying requested changes) is shown as
 * not connected, never simulated. Approving uses the existing approval checkpoint and means
 * a human reviewed the work; it never makes the work human-authored.
 */

type TabId = "understand" | "files" | "diff" | "tests" | "evidence" | "ask" | "final";

const tabs: Array<{ id: TabId; label: string; icon: typeof FileDiff }> = [
  { id: "understand", label: "Understand", icon: ClipboardCheck },
  { id: "files", label: "Files", icon: FileCode2 },
  { id: "diff", label: "Diff", icon: FileDiff },
  { id: "tests", label: "Tests", icon: TestTube2 },
  { id: "evidence", label: "Evidence", icon: ListChecks },
  { id: "ask", label: "Ask Squasher", icon: MessageSquareText },
  { id: "final", label: "Final review", icon: ShieldCheck }
];

export interface WorkspaceActions {
  approve: (actionId: ApprovalActionId) => Promise<void>;
  ask: (runId: string, question: string) => Promise<AskAnswer>;
  requestChange: (runId: string, text: string) => Promise<ChangeRequestView>;
}

export function ContributionWorkspace({
  run,
  actions,
  pendingAction,
  approvalError,
  approvalMessage,
  initialTab = "understand"
}: {
  run: DashboardRun;
  actions: WorkspaceActions;
  pendingAction?: ApprovalActionId;
  approvalError?: string;
  approvalMessage?: string;
  initialTab?: TabId;
}) {
  const [recorded, setRecorded] = useState<ChangeRequestView[]>([]);
  // Requests recorded on this page count at once, before the next refresh brings them back
  // from the server, so the review state never contradicts what was just recorded.
  const known = run.changeRequests ?? [];
  const changeRequests = [...known, ...recorded.filter((entry) => !known.some((existing) => existing.id === entry.id))];
  const model = buildWorkspace({ ...run, changeRequests });
  const [tab, setTab] = useState<TabId>(initialTab);
  const [selectedPath, setSelectedPath] = useState<string | undefined>(model.files[0]?.path);
  const [dialog, setDialog] = useState<"request" | "approve" | undefined>();
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const idPrefix = useId();

  function openFile(path: string, target: TabId = "diff") {
    setSelectedPath(path);
    setTab(target);
  }

  function onTabKey(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    const move = event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : event.key === "Home" ? -index : event.key === "End" ? tabs.length - 1 - index : 0;
    if (!move) return;
    event.preventDefault();
    const next = (index + move + tabs.length) % tabs.length;
    setTab(tabs[next]!.id);
    tabRefs.current[next]?.focus();
  }

  const backHref = run.harness.dashboardUrl ?? `/runs/${encodeURIComponent(run.id)}`;

  if (!model.available) {
    return (
      <section className="workspace" aria-labelledby={`${idPrefix}-title`}>
        <a className="back-link" href={backHref}><ArrowLeft size={14} />Back to run overview</a>
        <div className="panel workspace-empty">
          <PanelTitle eyebrow="Contribution workspace" title="Nothing to review" icon={<ClipboardCheck size={17} />} />
          <p id={`${idPrefix}-title`}>{model.unavailableReason}</p>
        </div>
      </section>
    );
  }

  const withRequests = model;
  return (
    <section className="workspace" aria-labelledby={`${idPrefix}-title`}>
      <div className="workspace-heading">
        <a className="back-link" href={backHref}><ArrowLeft size={14} />Back to run overview</a>
        <p className="eyebrow">Contribution workspace</p>
        <h2 id={`${idPrefix}-title`}>{run.candidatePatch?.title ?? run.issueTitle}</h2>
        <p className="workspace-authorship">
          <Bot size={15} aria-hidden="true" />
          <span>
            This patch was generated by Squasher, an automated agent. Approving records that a human reviewed it
            and wants to continue; it does not make the work human-authored.
          </span>
        </p>
      </div>

      <WorkspaceSummary model={withRequests} />

      <div className="workspace-tabs" role="tablist" aria-label="Contribution workspace sections">
        {tabs.map(({ id, label, icon: Icon }, index) => (
          <button
            key={id}
            ref={(element) => { tabRefs.current[index] = element; }}
            type="button"
            role="tab"
            id={`${idPrefix}-tab-${id}`}
            aria-selected={tab === id}
            aria-controls={`${idPrefix}-panel-${id}`}
            tabIndex={tab === id ? 0 : -1}
            className={tab === id ? "active" : undefined}
            onClick={() => setTab(id)}
            onKeyDown={(event) => onTabKey(event, index)}
          >
            <Icon size={15} aria-hidden="true" />{label}
          </button>
        ))}
      </div>

      <div className="panel workspace-panel" role="tabpanel" id={`${idPrefix}-panel-${tab}`} aria-labelledby={`${idPrefix}-tab-${tab}`}>
        {tab === "understand" ? <UnderstandView model={withRequests} openFile={openFile} /> : undefined}
        {tab === "files" ? <FilesView model={withRequests} selectedPath={selectedPath} onSelect={setSelectedPath} openFile={openFile} /> : undefined}
        {tab === "diff" ? <DiffView model={withRequests} selectedPath={selectedPath} onSelect={setSelectedPath} /> : undefined}
        {tab === "tests" ? <TestsView run={run} model={withRequests} /> : undefined}
        {tab === "evidence" ? <EvidenceView run={run} model={withRequests} /> : undefined}
        {tab === "ask" ? <AskView run={run} ask={actions.ask} /> : undefined}
        {tab === "final" ? <FinalReview run={run} model={withRequests} goTo={setTab} /> : undefined}
      </div>

      <div className="workspace-actions" role="group" aria-label="Review actions">
        <button type="button" className="button" onClick={() => setDialog("request")}><PencilLine size={16} aria-hidden="true" />Request changes</button>
        <button type="button" className="button" disabled aria-describedby={`${idPrefix}-tests-note`}><RefreshCw size={16} aria-hidden="true" />Run tests</button>
        <button type="button" className="button" onClick={() => setTab("final")}><FileDiff size={16} aria-hidden="true" />Review final diff</button>
        <button
          type="button"
          className="button button-success"
          disabled={!model.approval.possible || pendingAction !== undefined}
          aria-describedby={`${idPrefix}-approve-note`}
          onClick={() => setDialog("approve")}
        >
          <GitPullRequestArrow size={16} aria-hidden="true" />{pendingAction === "approve-pr" ? "Approving" : "Approve contribution"}
        </button>
        <p className="workspace-action-note" id={`${idPrefix}-tests-note`}>
          Run tests is not connected yet: the workspace cannot re-run tests. Results shown are from the run.
        </p>
        <p className="workspace-action-note" id={`${idPrefix}-approve-note`}>{model.approval.reason}</p>
        {approvalError ? <p className="workspace-action-note error" role="alert">{approvalError}</p> : undefined}
        {approvalMessage ? <p className="workspace-action-note" role="status">{approvalMessage}</p> : undefined}
      </div>

      {dialog === "request" ? (
        <RequestChangesDialog
          onClose={() => setDialog(undefined)}
          onSubmit={async (text) => {
            const created = await actions.requestChange(run.id, text);
            setRecorded((current) => [...current, created]);
          }}
        />
      ) : undefined}
      {dialog === "approve" ? (
        <ApproveDialog
          model={withRequests}
          onClose={() => setDialog(undefined)}
          onConfirm={async () => {
            setDialog(undefined);
            await actions.approve("approve-pr");
          }}
        />
      ) : undefined}
    </section>
  );
}

function WorkspaceSummary({ model }: { model: WorkspaceModel }) {
  const tests = model.tests;
  return (
    <dl className="workspace-summary" aria-label="Review status">
      <div className="summary-card status-success">
        <dt>Implementation</dt>
        <dd>{model.implementation?.label ?? "Not reported"}</dd>
      </div>
      <div className="summary-card">
        <dt>Requirements</dt>
        <dd>{model.requirements.counted ? `${model.requirements.satisfied} / ${model.requirements.counted} satisfied` : "Not recorded"}</dd>
      </div>
      <div className="summary-card">
        <dt>Tests</dt>
        <dd>
          {tests.passed !== undefined
            ? `${tests.passed} passed${tests.failed !== undefined ? `, ${tests.failed} failed` : ""}`
            : "No structured count"}
        </dd>
        {tests.passed !== undefined ? <small>As reported by the agent</small> : undefined}
      </div>
      <div className={`summary-card ${model.policy && !model.policy.automaticContributionAllowed ? "status-warning" : ""}`}>
        <dt>Repository policy</dt>
        <dd>{model.policy?.label ?? "Not available"}</dd>
      </div>
      <div className={`summary-card ${model.review.state === "blocked-by-policy" || model.review.state === "changes-requested" ? "status-warning" : model.review.state === "submitted" ? "status-success" : "status-active"}`}>
        <dt>Review</dt>
        <dd>{model.review.label}</dd>
      </div>
    </dl>
  );
}

function UnderstandView({ model, openFile }: { model: WorkspaceModel; openFile: (path: string) => void }) {
  return (
    <>
      <PanelTitle eyebrow="Understand" title="What changed and why" icon={<ClipboardCheck size={17} />} />
      <ul className="change-cards">
        {model.files.map((file) => (
          <li key={file.path} className="change-card">
            <div className="change-card-head">
              <code>{file.path}</code>
              <ChangeBadge file={file} />
            </div>
            <dl>
              <div>
                <dt>Why it changed</dt>
                <dd>
                  {file.explanation ? (
                    <><MarkdownContent value={file.explanation.summary} /><SourceTag source="agent" /></>
                  ) : (
                    <span className="unavailable">Explanation not available from the current run data.</span>
                  )}
                </dd>
              </div>
              <div>
                <dt>Requirement</dt>
                <dd>
                  {file.explanation?.requirements.length ? (
                    <ul className="plain-list">{file.explanation.requirements.map((text) => <li key={text}>{text}</li>)}</ul>
                  ) : (
                    <span className="unavailable">Mapping not available from the current run data.</span>
                  )}
                </dd>
              </div>
              <div>
                <dt>Tests and evidence</dt>
                <dd><span className="unavailable">Evidence is recorded for the patch as a whole, not per file. See Tests and Evidence.</span></dd>
              </div>
            </dl>
            <button type="button" className="button" onClick={() => openFile(file.path)}><FileDiff size={15} aria-hidden="true" />View exact change</button>
          </li>
        ))}
      </ul>

      <h3 className="workspace-subheading">Requirement → file mapping</h3>
      {model.mapping?.length ? (
        <ul className="mapping-list">
          {model.mapping.map((entry) => (
            <li key={entry.requirement}>
              <span>{entry.requirement}</span>
              <span aria-hidden="true">→</span>
              <span>{entry.files.map((path) => <button key={path} type="button" className="link-button" onClick={() => openFile(path)}>{path}</button>)}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="unavailable">Mapping not available from the current run data.</p>
      )}
    </>
  );
}

function ChangeBadge({ file }: { file: WorkspaceFile }) {
  const label = file.change === "added" ? "Added" : file.change === "modified" ? "Modified" : "Base unknown";
  return (
    <span className={`change-badge change-${file.change}`}>
      {label}
      {file.diff ? <> · <span aria-label={`${file.diff.additions} lines added`}>+{file.diff.additions}</span> <span aria-label={`${file.diff.deletions} lines removed`}>−{file.diff.deletions}</span></> : undefined}
    </span>
  );
}

function FileNav({ model, selectedPath, onSelect, label }: { model: WorkspaceModel; selectedPath?: string; onSelect: (path: string) => void; label: string }) {
  return (
    <nav className="file-nav" aria-label={label}>
      <p className="eyebrow">Files changed ({model.files.length})</p>
      <ul>
        {model.files.map((file) => (
          <li key={file.path}>
            <button type="button" aria-current={selectedPath === file.path ? "true" : undefined} onClick={() => onSelect(file.path)}>
              <FileCode2 size={14} aria-hidden="true" /><span>{file.path}</span><ChangeBadge file={file} />
            </button>
          </li>
        ))}
      </ul>
    </nav>
  );
}

function FilesView({ model, selectedPath, onSelect, openFile }: { model: WorkspaceModel; selectedPath?: string; onSelect: (path: string) => void; openFile: (path: string) => void }) {
  const file = model.files.find((entry) => entry.path === selectedPath) ?? model.files[0];
  return (
    <>
      <PanelTitle eyebrow="Files" title="Changed files" icon={<FileCode2 size={17} />} />
      <div className="workspace-split">
        <FileNav model={model} selectedPath={file?.path} onSelect={onSelect} label="Changed files" />
        {file ? (
          <div className="file-detail">
            <div className="change-card-head"><code>{file.path}</code><ChangeBadge file={file} /></div>
            {file.explanation ? <div className="file-why"><MarkdownContent value={file.explanation.summary} /><SourceTag source="agent" /></div> : undefined}
            <button type="button" className="button" onClick={() => openFile(file.path)}><FileDiff size={15} aria-hidden="true" />View diff</button>
            <p className="eyebrow">Proposed content</p>
            <pre className="workspace-code" tabIndex={0} aria-label={`Proposed content of ${file.path}`}>{file.after}</pre>
          </div>
        ) : undefined}
      </div>
    </>
  );
}

/** Lines rendered per file before the rest is hidden behind a button. */
const renderedDiffLines = 1_500;

function DiffView({ model, selectedPath, onSelect }: { model: WorkspaceModel; selectedPath?: string; onSelect: (path: string) => void }) {
  const file = model.files.find((entry) => entry.path === selectedPath) ?? model.files[0];
  return (
    <>
      <PanelTitle eyebrow="Diff" title="Exact change" icon={<FileDiff size={17} />} />
      <RevisionNote model={model} />
      <div className="workspace-split">
        <FileNav model={model} selectedPath={file?.path} onSelect={onSelect} label="Files in the diff" />
        {file ? <FileDiffView file={file} /> : undefined}
      </div>
    </>
  );
}

function RevisionNote({ model }: { model: WorkspaceModel }) {
  const { revisions } = model;
  return (
    <div className="revision-note" role="note">
      <span><strong>Original Squasher patch</strong> {revisions.original.files} file{revisions.original.files === 1 ? "" : "s"}</span>
      <span><strong>Human or requested changes applied</strong> {revisions.applied.length === 0 ? "none" : revisions.applied.length}</span>
      <span><strong>Current proposed patch</strong> {revisions.proposed.sameAsOriginal ? "same as the original" : `${revisions.proposed.files} files`}</span>
      {revisions.pendingRequests ? (
        <span className="unavailable">{revisions.pendingRequests} requested change{revisions.pendingRequests === 1 ? "" : "s"} recorded, not yet implemented.</span>
      ) : undefined}
    </div>
  );
}

function FileDiffView({ file }: { file: WorkspaceFile }) {
  const [showAll, setShowAll] = useState(false);
  if (!file.diff) {
    return (
      <div className="file-detail">
        <div className="change-card-head"><code>{file.path}</code><ChangeBadge file={file} /></div>
        <p className="unavailable">The original of this file could not be read from the repository, so no diff can be shown. The proposed content is below.</p>
        <pre className="workspace-code" tabIndex={0}>{file.after}</pre>
      </div>
    );
  }
  return (
    <div className="file-detail">
      <div className="change-card-head"><code>{file.path}</code><ChangeBadge file={file} /></div>
      {file.diff.approximate ? <p className="unavailable">This change is too large to align line by line; the whole file is shown replaced.</p> : undefined}
      <DiffTable diff={file.diff} path={file.path} limit={showAll ? Infinity : renderedDiffLines} />
      {!showAll && countLines(file.diff) > renderedDiffLines ? (
        <button type="button" className="button" onClick={() => setShowAll(true)}>Show all {countLines(file.diff)} lines</button>
      ) : undefined}
    </div>
  );
}

function countLines(diff: FileDiffModel): number {
  return diff.hunks.reduce((sum, hunk) => sum + hunk.lines.length, 0);
}

function DiffTable({ diff, path, limit }: { diff: FileDiffModel; path: string; limit: number }) {
  let rendered = 0;
  return (
    <div className="diff-scroll" tabIndex={0} role="region" aria-label={`Diff of ${path}`}>
      <table className="diff-table">
        <thead className="visually-hidden">
          <tr><th scope="col">Original line</th><th scope="col">New line</th><th scope="col">Change</th><th scope="col">Content</th></tr>
        </thead>
        {diff.hunks.map((hunk, index) => {
          if (rendered >= limit) return undefined;
          const lines = hunk.lines.slice(0, Math.max(0, limit - rendered));
          rendered += lines.length;
          return (
            <tbody key={`${hunk.oldStart}-${hunk.newStart}-${index}`}>
              {hunk.skippedBefore > 0 ? (
                <tr className="diff-skip"><td colSpan={4}>{hunk.skippedBefore} unchanged line{hunk.skippedBefore === 1 ? "" : "s"}</td></tr>
              ) : undefined}
              {lines.map((line, lineIndex) => (
                <tr key={lineIndex} className={`diff-${line.kind}`}>
                  <td className="diff-number">{line.oldNumber ?? ""}</td>
                  <td className="diff-number">{line.newNumber ?? ""}</td>
                  <td className="diff-marker" aria-label={line.kind === "added" ? "added" : line.kind === "removed" ? "removed" : "unchanged"}>
                    {line.kind === "added" ? "+" : line.kind === "removed" ? "−" : " "}
                  </td>
                  <td className="diff-text"><code>{line.text || " "}</code></td>
                </tr>
              ))}
            </tbody>
          );
        })}
      </table>
    </div>
  );
}

function TestsView({ run, model }: { run: DashboardRun; model: WorkspaceModel }) {
  const commands = run.harness.trace.filter((event) => event.category === "sandbox" && event.command && /\b(?:test|pytest|vitest|jest|spec|repro|check|lint|build)\b/i.test(event.command));
  const proof = run.proof;
  return (
    <>
      <PanelTitle eyebrow="Tests" title="Tests and verification" icon={<TestTube2 size={17} />} />
      <div className="evidence-note" role="note">
        <AlertTriangle size={16} aria-hidden="true" />
        <span>Re-running tests from the workspace is not connected yet. Everything below was recorded during the run.</span>
      </div>
      <dl className="proof-list">
        <div><dt>Attempts</dt><dd>{proof?.attempts ? <MarkdownContent value={proof.attempts} /> : <span className="unavailable">Not recorded.</span>}</dd></div>
        <div><dt>Before the change</dt><dd>{proof?.before ? <MarkdownContent value={proof.before} /> : <span className="unavailable">Not recorded.</span>}</dd></div>
        <div><dt>After the change</dt><dd>{proof?.after ? <MarkdownContent value={proof.after} /> : <span className="unavailable">Not recorded.</span>}</dd></div>
        <div><dt>Regression checks</dt><dd>{proof?.regressions ? <MarkdownContent value={proof.regressions} /> : <span className="unavailable">Not recorded.</span>}</dd></div>
      </dl>
      <SourceTag source="agent" />
      {model.tests.passed !== undefined ? (
        <p className="workspace-small">Counts in the summary are read from the regression text above; they are the agent's report, not a separate measurement.</p>
      ) : undefined}
      <h3 className="workspace-subheading">Test commands in the trace</h3>
      {commands.length ? (
        <ul className="command-list">
          {commands.map((event) => (
            <li key={event.id}><code>{event.command}</code><SourceTag source="trace" /></li>
          ))}
        </ul>
      ) : (
        <p className="unavailable">No test commands are in the retained trace.</p>
      )}
    </>
  );
}

function EvidenceView({ run, model }: { run: DashboardRun; model: WorkspaceModel }) {
  return (
    <>
      <PanelTitle eyebrow="Evidence" title="Requirements and evidence" icon={<ListChecks size={17} />} />
      {model.requirements.items.length ? (
        <ul className="requirement-grid">
          {model.requirements.items.map((requirement) => (
            <li key={requirement.requirement} className={`requirement requirement-${requirement.verdict}`}>
              <span className="requirement-verdict">{verdictText(requirement.verdict)}</span>
              <div>
                <MarkdownContent value={requirement.requirement} />
                {requirement.evidence ? <MarkdownContent value={requirement.evidence} className="requirement-evidence" /> : <span className="unavailable">No evidence recorded.</span>}
                {requirement.codeEvidence?.map((cited) => (
                  <p key={`${cited.path}:${cited.excerpt}`} className="cited-code"><code>{cited.path}</code>: <code>{cited.excerpt}</code></p>
                ))}
                {requirement.executedCommand ? <p className="cited-code">Command: <code>{requirement.executedCommand}</code></p> : undefined}
                {requirement.ownership ? <span className="requirement-owner">{requirement.ownership.status} · {requirement.ownership.by}</span> : undefined}
              </div>
            </li>
          ))}
        </ul>
      ) : (
        <p className="unavailable">This run recorded no requirement verification.</p>
      )}
      <SourceTag source="agent" />
      {run.discussionClaims?.length ? (
        <>
          <h3 className="workspace-subheading">Discussion claims checked against the repository</h3>
          <ul className="requirement-grid">
            {run.discussionClaims.map((claim) => (
              <li key={claim.claim} className={`claim claim-${claim.verdict}`}>
                <span className="requirement-verdict">{claim.verdict}</span>
                <div>
                  <p className="claim-label">The discussion says</p><MarkdownContent value={claim.claim} />
                  <p className="claim-label">The repository shows</p><MarkdownContent value={claim.evidence} />
                </div>
              </li>
            ))}
          </ul>
        </>
      ) : undefined}
    </>
  );
}

function verdictText(verdict: string): string {
  return verdict === "pass" ? "Pass" : verdict === "fail" ? "Fail" : verdict === "already-implemented" ? "Already implemented" : verdict === "missing" ? "Missing" : verdict === "out-of-scope" ? "Out of scope" : verdict;
}

function AskView({ run, ask }: { run: DashboardRun; ask: WorkspaceActions["ask"] }) {
  const [question, setQuestion] = useState("");
  const [answers, setAnswers] = useState<AskAnswer[]>([]);
  const [error, setError] = useState<string | undefined>();
  const [busy, setBusy] = useState(false);
  const inputId = useId();
  const suggestions = ["Why did you change this file?", "Which requirement does each change satisfy?", "Could this change affect anything else?", "What tests prove this works?"];

  async function submit(text: string) {
    if (text.trim().length < 3) return;
    setBusy(true);
    setError(undefined);
    try {
      const answer = await ask(run.id, text.trim());
      setAnswers((current) => [answer, ...current]);
      setQuestion("");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Squasher did not answer");
    } finally {
      setBusy(false);
    }
  }

  return (
    <>
      <PanelTitle eyebrow="Ask Squasher" title="Questions about this run" icon={<MessageSquareText size={17} />} />
      <p className="workspace-small">Answers come from this run's issue, discussion, patch, requirements, tests and evidence only. When something is not in the run, the answer says so. Asking needs the maintainer token.</p>
      <div className="suggestions" role="group" aria-label="Suggested questions">
        {suggestions.map((text) => <button key={text} type="button" className="button" disabled={busy} onClick={() => void submit(text)}>{text}</button>)}
      </div>
      <form className="ask-form" onSubmit={(event) => { event.preventDefault(); void submit(question); }}>
        <label htmlFor={inputId}>Your question</label>
        <textarea id={inputId} value={question} rows={3} maxLength={1000} onChange={(event) => setQuestion(event.target.value)} />
        <button type="submit" className="button button-primary" disabled={busy || question.trim().length < 3}><Send size={15} aria-hidden="true" />{busy ? "Asking" : "Ask"}</button>
      </form>
      {error ? <p className="workspace-action-note error" role="alert">{error}</p> : undefined}
      <ol className="answers" aria-live="polite">
        {answers.map((answer) => (
          <li key={answer.answeredAt + answer.question}>
            <p className="answer-question">{answer.question}</p>
            <MarkdownContent value={answer.answer} />
            <p className="workspace-small">Generated by Squasher's model from this run's data.{answer.missingSections.length ? ` Not available to it: ${answer.missingSections.join(", ")}.` : ""}</p>
          </li>
        ))}
      </ol>
    </>
  );
}

function FinalReview({ run, model, goTo }: { run: DashboardRun; model: WorkspaceModel; goTo: (tab: TabId) => void }) {
  const [copied, setCopied] = useState<string | undefined>();
  const exportable = model.files.filter((file) => file.change !== "unknown");
  const excluded = model.files.filter((file) => file.change === "unknown");
  const patchText = exportable.length
    ? unifiedPatch(exportable.map((file) => ({ path: file.path, before: file.before ?? "", after: file.after, added: file.change === "added" })))
    : undefined;
  const prohibited = model.policy && !model.policy.automaticContributionAllowed;

  async function copyPatch() {
    if (!patchText) return;
    try {
      await navigator.clipboard.writeText(patchText);
      setCopied("Patch copied");
    } catch {
      setCopied("Copy failed: your browser blocked clipboard access");
    }
  }

  return (
    <>
      <PanelTitle eyebrow="Final review" title="Before any contribution" icon={<ShieldCheck size={17} />} />
      <dl className="final-review">
        <div><dt>Implementation</dt><dd>{model.implementation?.label ?? "Not reported"}</dd></div>
        <div><dt>Requirements</dt><dd>{model.requirements.counted ? `${model.requirements.satisfied} / ${model.requirements.counted} satisfied` : "Not recorded"}</dd></div>
        <div><dt>Tests</dt><dd>{model.tests.passed !== undefined ? `${model.tests.passed} passed${model.tests.failed !== undefined ? `, ${model.tests.failed} failed` : ""} (agent-reported)` : "No structured count; see Tests"}</dd></div>
        <div><dt>Files changed</dt><dd>{model.files.length}</dd></div>
        <div>
          <dt>Human modifications</dt>
          <dd>None applied.{model.changeRequests.length ? ` ${model.changeRequests.length} requested, not yet implemented by Squasher.` : ""}</dd>
        </div>
        <div><dt>Contribution</dt><dd>{model.contribution ? `${model.contribution.label}: ${model.contribution.reason}` : "Not available"}</dd></div>
      </dl>

      <div className={`policy-box ${prohibited ? "blocked" : ""}`}>
        <Scale size={17} aria-hidden="true" />
        <div>
          <strong>Repository policy: {model.policy?.label ?? "Not available"}</strong>
          {model.policy ? <><p>{model.policy.detail}</p><p><strong>Next step:</strong> {model.policy.nextStep}</p></> : <p className="unavailable">This run carries no policy information.</p>}
          {model.policy?.signals.length ? (
            <ul className="policy-findings">
              {model.policy.signals.map((signal) => <li key={`${signal.kind}:${signal.path}`}><code>{signal.path}</code> ({signal.kind}) — “{signal.excerpt}”</li>)}
            </ul>
          ) : undefined}
        </div>
      </div>

      {prohibited ? <p className="policy-verdict" role="note"><AlertTriangle size={16} aria-hidden="true" />Repository policy prohibits this contribution. Squasher will not create a pull request.</p> : undefined}

      {model.changeRequests.length ? (
        <>
          <h3 className="workspace-subheading">Requested changes</h3>
          <ul className="change-requests">
            {model.changeRequests.map((request) => (
              <li key={request.id}><MarkdownContent value={request.text} /><span className="requirement-owner">Recorded · not yet implemented</span></li>
            ))}
          </ul>
        </>
      ) : undefined}

      <div className="technical-links">
        <button type="button" className="button" onClick={() => goTo("diff")}><FileDiff size={15} aria-hidden="true" />View final diff</button>
        <button type="button" className="button" onClick={() => goTo("tests")}><TestTube2 size={15} aria-hidden="true" />View tests</button>
        <button type="button" className="button" onClick={() => goTo("evidence")}><ListChecks size={15} aria-hidden="true" />View evidence</button>
        {patchText ? (
          <>
            <button type="button" className="button" onClick={() => void copyPatch()}><Copy size={15} aria-hidden="true" />Copy patch</button>
            <a className="button" download={`squasher-${run.id}.patch`} href={`data:text/x-diff;charset=utf-8,${encodeURIComponent(patchText)}`}><Download size={15} aria-hidden="true" />Download patch</a>
          </>
        ) : undefined}
      </div>
      {copied ? <p className="workspace-small" role="status">{copied}</p> : undefined}
      {excluded.length ? <p className="unavailable">Not in the exported patch, because their original content is unknown: {excluded.map((file) => file.path).join(", ")}.</p> : undefined}
    </>
  );
}

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const titleId = useId();
  return (
    <div className="dialog-backdrop" onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}>
      <div className="dialog panel" role="dialog" aria-modal="true" aria-labelledby={titleId}>
        <div className="dialog-head">
          <h3 id={titleId}>{title}</h3>
          <button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={16} /></button>
        </div>
        {children}
      </div>
    </div>
  );
}

function RequestChangesDialog({ onClose, onSubmit }: { onClose: () => void; onSubmit: (text: string) => Promise<void> }) {
  const [text, setText] = useState("");
  const [state, setState] = useState<"editing" | "saving" | "recorded" | "error">("editing");
  const [error, setError] = useState<string | undefined>();
  const inputId = useId();

  async function submit() {
    setState("saving");
    setError(undefined);
    try {
      await onSubmit(text.trim());
      setState("recorded");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "The change request was not recorded");
      setState("error");
    }
  }

  return (
    <Dialog title="Request changes" onClose={onClose}>
      {state === "recorded" ? (
        <div role="status">
          <p><strong>Requested change:</strong> {text}</p>
          <p><strong>Status:</strong> Recorded, awaiting implementation. Squasher does not apply requested changes automatically yet, so the patch is unchanged.</p>
          <button type="button" className="button" onClick={onClose}><Check size={15} aria-hidden="true" />Done</button>
        </div>
      ) : (
        <form onSubmit={(event) => { event.preventDefault(); void submit(); }}>
          <label htmlFor={inputId}>Describe the change you want</label>
          <textarea id={inputId} rows={4} maxLength={2000} autoFocus value={text} onChange={(event) => setText(event.target.value)} placeholder="For example: Don't modify CHANGELOG.md." />
          <p className="workspace-small">The request is recorded against this run. It is not yet implemented automatically: nothing in the patch changes until it is.</p>
          {error ? <p className="workspace-action-note error" role="alert">{error}</p> : undefined}
          <button type="submit" className="button button-primary" disabled={state === "saving" || text.trim().length < 3}>{state === "saving" ? "Recording" : "Record request"}</button>
        </form>
      )}
    </Dialog>
  );
}

function ApproveDialog({ model, onClose, onConfirm }: { model: WorkspaceModel; onClose: () => void; onConfirm: () => Promise<void> }) {
  return (
    <Dialog title="Approve contribution" onClose={onClose}>
      <p>You are confirming that you reviewed this patch and want Squasher to continue with the contribution.</p>
      <ul className="plain-list">
        <li>The patch was generated by Squasher, an automated agent. Approving does not make it human-authored.</li>
        <li>{model.contribution?.reason ?? "The paused write resumes through the existing approval checkpoint."}</li>
        {model.policy ? <li>Repository policy: {model.policy.label}. {model.policy.nextStep}</li> : undefined}
      </ul>
      <div className="technical-links">
        <button type="button" className="button button-success" autoFocus onClick={() => void onConfirm()}><GitPullRequestArrow size={15} aria-hidden="true" />Approve and continue</button>
        <button type="button" className="button" onClick={onClose}>Cancel</button>
      </div>
    </Dialog>
  );
}
